const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
})

module.exports = withNextra({
  i18n: {
    locales: [
      'en-US',
      'zh-CN',
      'es-ES',
      'hi-IN',
      'ar-SA',
      'bn-IN',
      'pt-BR',
      'ru-RU',
      'ja-JP',
      'de-DE',
      'jv-ID',
      'ko-KR',
      'fr-FR',
      'tr-TR',
      'vi-VN',
      'ta-IN',
      'ur-PK',
      'fa-IR',
      'it-IT',
      'pl-PL',
      'uk-UA',
      'ro-RO',
      'nl-NL',
      'id-ID',
      'th-TH',
      'el-GR',
      'hu-HU',
      'sv-SE',
      'cs-CZ',
      'bg-BG',
    ],
    defaultLocale: 'en-US',
  },
})
